export const SHOW_HOVER_MENU = 'SHOW_HOVER_MENU';
export const HIDE_HOVER_MENU = 'HIDE_HOVER_MENU';

export const SHOW_PROFILE = 'SHOW_PROFILE';
export const HIDE_PROFILE = 'HIDE_PROFILE';

export const SHOW_MOBILE_SIDEBAR = 'SHOW_MOBILE_SIDEBAR';
export const HIDE_MOBILE_SIDEBAR = 'HIDE_MOBILE_SIDEBAR';

export const SET_MENU_CATEGORY = 'SET_MENU_CATEGORY';

export const SET_SHOW_SIZES_MODAL = 'SET_SHOW_SIZES_MODAL';

export const SET_SHOW_AUTH_MODAL = 'SET_SHOW_AUTH_MODAL';
export const SET_SHOW_REG_MODAL = 'SET_SHOW_REG_MODAL';
export const SET_SHOW_LOGOUT_MODAL = 'SET_SHOW_LOGOUT_MODAL';

export const SET_SHOW_REQUEST_MODAL = 'SET_SHOW_REQUEST_MODAL';
export const SET_SHOW_EDIT_USER_SUCCESS_MODAL = 'SET_SHOW_EDIT_USER_SUCCESS_MODAL';
export const SET_IS_MOBILE = 'SET_IS_MOBILE';
export const SET_IS_DISABLE_SCROLL = 'SET_IS_DISABLE_SCROLL';

export const SET_MOBILE_SORT_MODAL = 'SET_MOBILE_SORT_MODAL';
export const SET_MOBILE_FILTER_MODAL = 'SET_MOBILE_FILTER_MODAL';
export const SET_MOBILE_CART_MODAL = 'SET_MOBILE_CART_MODAL';
export const SET_SHOW_SELLER_THANKS_MODAL = 'SET_SHOW_SELLER_THANKS_MODAL';
export const SET_SHOW_SUBSCRIBE_THANKS_MODAL = 'SET_SHOW_SUBSCRIBE_THANKS_MODAL';
export const SET_SHOW_SUBSCRIBE_ERROR_MODAL = 'SET_SHOW_SUBSCRIBE_ERROR_MODAL';
export const SET_SHOW_REQUEST_THANKS_MODAL = 'SET_SHOW_REQUEST_THANKS_MODAL';
export const SET_SHOW_REQUEST_ERROR_MODAL = 'SET_SHOW_REQUEST_ERROR_MODAL';
export const SET_SHOW_EDIT_USER_MODAL = 'SET_SHOW_EDIT_USER_MODAL';
export const SET_BREADCRUMBS = 'SET_BREADCRUMBS';
export const SET_REMOVE_FROM_SALE_MODAL = 'SET_REMOVE_FROM_SALE_MODAL';
export const SET_REMOVE_FROM_SALE_SUCCESS_MODAL = 'SET_REMOVE_FROM_SALE_SUCCESS_MODAL';
export const SET_REMOVE_MODAL = 'SET_REMOVE_MODAL';
export const SET_REMOVE_SUCCESS_MODAL = 'SET_REMOVE_SUCCESS_MODAL';
export const SET_PHOTO_RECOMEND_MODAL = 'SET_PHOTO_RECOMEND_MODAL';
export const SET_CHANGE_PASS_MODAL = 'SET_CHANGE_PASS_MODAL';
export const SET_CHANGE_PASS_SUCCESS_MODAL = 'SET_CHANGE_PASS_SUCCESS_MODAL';
export const SET_RESET_PASS_MODAL = 'SET_RESET_PASS_MODAL';
export const SET_RESET_PASS_SUCCESS_MODAL = 'SET_RESET_PASS_SUCCESS_MODAL';
export const SET_RESALE_MODAL = 'SET_RESALE_MODAL';
export const SET_RESALE_SUCCESS_MODAL = 'SET_RESALE_SUCCESS_MODAL';
export const SET_PUBLISH_MODAL = 'SET_PUBLISH_MODAL';
export const SET_PUBLISH_SUCCESS_MODAL = 'SET_PUBLISH_SUCCESS_MODAL';
