export const SET_CART_PRODUCTS = 'SET_CART_PRODUCTS';
export const SET_CART_PRODUCTS_LOADING = 'SET_CART_PRODUCTS_LOADING';
export const SET_CART_PRODUCTS_ERROR = 'SET_CART_PRODUCTS_ERROR';
export const SET_CART_LOCAL = 'SET_CART_LOCAL';
export const SET_CART_TOTAL = 'SET_CART_TOTAL';

export const ORDERING_SUCCESS = 'ORDERING_SUCCESS';
export const ORDERING_LOADING = 'ORDERING_LOADING';
export const ORDERING_ERROR = 'ORDERING_ERROR';
