export const SET_CART_PRODUCTS = 'SET_CART_PRODUCTS';
export const SET_CART_PRODUCTS_LOADING = 'SET_CART_PRODUCTS_LOADING';
export const SET_CART_PRODUCTS_ERROR = 'SET_CART_PRODUCTS_ERROR';
export const SET_CART_LOCAL = 'SET_CART_LOCAL';
export const SET_CART_TOTAL = 'SET_CART_TOTAL';
