export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING';
export const SET_PRODUCTS_ERROR = 'SET_PRODUCTS_ERROR';
export const SET_OPENED_PRODUCT = 'SET_OPENED_PRODUCT';
export const SET_OPENED_PRODUCT_LOADING = 'SET_OPENED_PRODUCT_LOADING';
export const SET_OPENED_PRODUCT_ERROR = 'SET_OPENED_PRODUCT_ERROR';
export const SET_SHARE_PRODUCT = 'SET_SHARE_PRODUCT';
export const SET_SIZES = 'SET_SIZES';
export const SET_NEW_PRODUCTS = 'SET_NEW_PRODUCTS';
export const SET_TRENDS = 'SET_TRENDS';

export const UPLOAD_IMAGES_LOADING = 'UPLOAD_IMAGES_LOADING';
export const UPLOAD_IMAGES_ERROR = 'UPLOAD_IMAGES_ERROR';
export const UPLOAD_IMAGES_SUCCESS = 'UPLOAD_IMAGES_SUCCESS';

export const UPLOAD_DETAILS_LOADING = 'UPLOAD_DETAILS_LOADING';
export const UPLOAD_DETAILS_ERROR = 'UPLOAD_DETAILS_ERROR';
export const UPLOAD_DETAILS_SUCCESS = 'UPLOAD_DETAILS_SUCCESS';

export const UPLOAD_VARIATIONS_LOADING = 'UPLOAD_VARIATIONS_LOADING';
export const UPLOAD_VARIATIONS_ERROR = 'UPLOAD_VARIATIONS_ERROR';
export const UPLOAD_VARIATIONS_SUCCESS = 'UPLOAD_VARIATIONS_SUCCESS';

export const ADD_PRODUCT_LOADING = 'ADD_PRODUCT_LOADING';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';

export const EDIT_PRODUCT_LOADING = 'EDIT_PRODUCT_LOADING';
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';

export const ADD_FAVORITE_LOADING = 'ADD_FAVORITE_LOADING';
export const ADD_FAVORITE_ERROR = 'ADD_FAVORITE_ERROR';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';

export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';
export const GET_FAVORITES_ERROR = 'GET_FAVORITES_ERROR';
export const GET_FAVORITES_LOADING = 'GET_FAVORITES_LOADING';

export const REMOVE_FAVORITE_SUCCESS = 'REMOVE_FAVORITES_SUCCESS';
export const REMOVE_FAVORITE_ERROR = 'REMOVE_FAVORITES_ERROR';
export const REMOVE_FAVORITE_LOADING = 'REMOVE_FAVORITES_LOADING';

export const UPDATE_COUNT_CART = 'UPDATE_COUNT_CART';
export const UPDATE_COUNT_FAVORITE = 'UPDATE_COUNT_FAVORITE';

export const GET_FAVORITE_PRODUCTS_SUCCESS = 'GET_FAVORITE_PRODUCTS_SUCCESS';
export const GET_FAVORITE_PRODUCTS_ERROR = 'GET_FAVORITE_PRODUCTS_ERROR';
export const GET_FAVORITE_PRODUCTS_LOADING = 'GET_FAVORITE_PRODUCTS_LOADING';

export const GET_EDIT_PRODUCT_SUCCESS = 'GET_EDIT_PRODUCT_SUCCESS';
export const GET_EDIT_PRODUCT_ERROR = 'GET_EDIT_PRODUCT_ERROR';
export const GET_EDIT_PRODUCT_LOADING = 'GET_EDIT_PRODUCT_LOADING';
export const RESET_SELL_PRODUCT_PAGE = 'RESET_SELL_PRODUCT_PAGE';

export const REMOVE_FROM_SALE_SUCCESS = 'REMOVE_FROM_SALE_SUCCESS';
export const REMOVE_FROM_SALE_ERROR = 'REMOVE_FROM_SALE_ERROR';
export const REMOVE_FROM_SALE_LOADING = 'REMOVE_FROM_SALE_LOADING';

export const REMOVE_SOFT_SUCCESS = 'REMOVE_SOFT_SUCCESS';
export const REMOVE_SOFT_ERROR = 'REMOVE_SOFT_ERROR';
export const REMOVE_SOFT_LOADING = 'REMOVE_SOFT_LOADING';

export const SET_SELECTED_PRODUCT_PROFILE = 'SET_SELECTED_PRODUCT_PROFILE';

export const GET_SELL_PRODUCTS_SUCCESS = 'GET_SELL_PRODUCTS_SUCCESS';
export const GET_SELL_PRODUCTS_ERROR = 'GET_SELL_PRODUCTS_ERROR';
export const GET_SELL_PRODUCTS_LOADING = 'GET_SELL_PRODUCTS_LOADING';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const RESET_REMOVE_FROM_SALE = 'RESET_REMOVE_FROM_SALE';
export const RESET_REMOVE_SOFT = 'RESET_REMOVE_SOFT';

export const GET_PURCHASED_PRODUCTS_SUCCESS = 'GET_PURCHASED_PRODUCTS_SUCCESS';
export const GET_PURCHASED_PRODUCTS_ERROR = 'GET_PURCHASED_PRODUCTS_ERROR';
export const GET_PURCHASED_PRODUCTS_LOADING = 'GET_PURCHASED_PRODUCTS_LOADING';
export const RESALE_SUCCESS = 'RESALE_SUCCESS';
export const RESALE_ERROR = 'RESALE_ERROR';
export const RESALE_LOADING = 'RESALE_LOADING';
export const RESET_RESALE = 'RESET_RESALE';

export const PUBLISH_SUCCESS = 'PUBLISH_SUCCESS';
export const PUBLISH_ERROR = 'PUBLISH_ERROR';
export const PUBLISH_LOADING = 'PUBLISH_LOADING';
export const RESET_PUBLISH = 'RESET_PUBLISH';

export const RELEVANT_CART_SUCCESS = 'RELEVANT_CART_SUCCESS';
export const RELEVANT_CART_LOADING = 'RELEVANT_CART_LOADING';
export const RELEVANT_CART_ERROR = 'RELEVANT_CART_ERROR';
