export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING';
export const SET_PRODUCTS_ERROR = 'SET_PRODUCTS_ERROR';
export const SET_OPENED_PRODUCT = 'SET_OPENED_PRODUCT';
export const SET_SHARE_PRODUCT = 'SET_SHARE_PRODUCT';
export const SET_SIZES = 'SET_SIZES';
export const SET_NEW_PRODUCTS = 'SET_NEW_PRODUCTS';
export const SET_TRENDS = 'SET_TRENDS';

export const UPLOAD_IMAGES_LOADING = 'UPLOAD_IMAGES_LOADING';
export const UPLOAD_IMAGES_ERROR = 'UPLOAD_IMAGES_ERROR';
export const UPLOAD_IMAGES_SUCCESS = 'UPLOAD_IMAGES_SUCCESS';

export const UPLOAD_DETAILS_LOADING = 'UPLOAD_DETAILS_LOADING';
export const UPLOAD_DETAILS_ERROR = 'UPLOAD_DETAILS_ERROR';
export const UPLOAD_DETAILS_SUCCESS = 'UPLOAD_DETAILS_SUCCESS';

export const ADD_PRODUCT_LOADING = 'ADD_PRODUCT_LOADING';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';

export const ADD_FAVORITE_LOADING = 'ADD_FAVORITE_LOADING';
export const ADD_FAVORITE_ERROR = 'ADD_FAVORITE_ERROR';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';
export const RESET_ADD_PRODUCTS = 'RESET_ADD_PRODUCTS';
