export const SET_SEARCH_PRODUCTS = 'SET_SEARCH_PRODUCTS';
export const SET_SHOW_SEARCH = 'SET_SHOW_SEARCH';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_SEARCH_CATEGORIES = 'SET_SEARCH_CATEGORIES';
export const SEARCH_RESET = 'SEARCH_RESET';
