export const SET_USER = 'SET_USER';
export const SET_USER_LOADING = 'SET_USER_LOADING';
export const SET_USER_ERROR = 'SET_USER_ERROR';
export const LOGOUT = 'LOGOUT';

export const SET_BUY_ITEMS = 'SET_BUY_ITEMS';
export const SET_SELL_ITEMS = 'SET_SELL_ITEMS';
export const SET_WISH_LIST = 'SET_WISH_LIST';

export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_LOADING = 'USER_LOADING';
export const USER_ERROR = 'USER_ERROR';
export const USER_RESET = 'USER_RESET';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';
export const EDIT_USER_LOADING = 'EDIT_USER_LOADING';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_IS_AUTH = 'SET_IS_AUTH';
export const SET_IS_AUTH_LOADING = 'SET_IS_AUTH_LOADING';
export const SET_IS_AUTH_SUCCESS = 'SET_IS_AUTH_SUCCESS';
export const SET_IS_AUTH_ERROR = 'SET_IS_AUTH_ERROR';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOADING';
